<?php
namespace backend\controllers;
use backend\models\{AcademicCalendar,KrsBlock,StudyProgram};use common\models\Student;use Yii;use yii\data\ActiveDataProvider;use yii\filters\{AccessControl,VerbFilter};use yii\helpers\ArrayHelper;use yii\web\{Controller,NotFoundHttpException};
class KrsBlockController extends Controller
{
    public function behaviors(){return ['access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['@']]]],'verbs'=>['class'=>VerbFilter::class,'actions'=>['delete'=>['POST'],'toggle'=>['POST']]]];}
    public function actionIndex($academic_period=null,$study_program_id=null,$entry_year=null,$q=null){$periods=$this->periodOptions();$programs=$this->programOptions();$academic_period=$academic_period?:array_key_first($periods);$study_program_id=$study_program_id?:array_key_first($programs);$query=KrsBlock::find()->alias('kb')->joinWith(['student.user','studyProgram'])->andFilterWhere(['kb.academic_period'=>$academic_period,'kb.study_program_id'=>$study_program_id,'kb.entry_year'=>$entry_year]);if(trim((string)$q)!=='')$query->andWhere(['or',['like','students.student_nationality_number',$q],['like','users.name',$q]]);$dataProvider=new ActiveDataProvider(['query'=>$query->orderBy('users.name'),'pagination'=>['pageSize'=>10,'pageSizeLimit'=>[5,100]],'sort'=>false]);$entryYears=array_combine($years=range((int)date('Y'),(int)date('Y')-10),$years);return $this->render('index',compact('dataProvider','periods','programs','academic_period','study_program_id','entry_year','entryYears','q'));}
    public function actionCreate(){$model=new KrsBlock(['academic_period'=>array_key_first($this->periodOptions()),'study_program_id'=>array_key_first($this->programOptions()),'entry_year'=>date('Y'),'current_semester'=>1]);return $this->saveForm($model,'create','Data Cekal KRS berhasil ditambahkan.');}
    public function actionUpdate($id){return $this->saveForm($this->findModel($id),'update','Data Cekal KRS berhasil diperbarui.');}
    public function actionView($id){return $this->render('view',['model'=>$this->findModel($id)]);}
    public function actionToggle($id){$model=$this->findModel($id);$attribute=Yii::$app->request->post('attribute');if(!array_key_exists($attribute,KrsBlock::blockAttributes()))return $this->asJson(['success'=>false,'message'=>'Jenis cekal tidak valid.']);$model->$attribute=(bool)Yii::$app->request->post('value');if($model->save())return $this->asJson(['success'=>true,'message'=>'Status cekal berhasil diperbarui.','active'=>$model->$attribute]);return $this->asJson(['success'=>false,'message'=>implode(' ',$model->getFirstErrors())]);}
    public function actionDelete($id){$this->findModel($id)->delete();return Yii::$app->request->isAjax?$this->asJson(['success'=>true,'message'=>'Data Cekal KRS berhasil dihapus.']):$this->redirect(['index']);}
    private function saveForm(KrsBlock $model,$view,$message){if($model->load(Yii::$app->request->post())&&$model->save()){Yii::$app->session->setFlash('success',$message);return $this->redirect(['view','id'=>$model->id]);}return $this->render($view,$this->formParams($model));}
    private function formParams($model){return ['model'=>$model,'periods'=>$this->periodOptions(),'programs'=>$this->programOptions(),'students'=>ArrayHelper::map(Student::find()->joinWith('user')->orderBy('users.name')->all(),'id',static fn($s)=>$s->student_nationality_number.' - '.$s->user->name)];}
    private function periodOptions(){return array_combine($p=AcademicCalendar::find()->select('period')->distinct()->orderBy(['period'=>SORT_DESC])->column(),$p)?:[];}private function programOptions(){return ArrayHelper::map(StudyProgram::find()->where(['is_active'=>1])->orderBy('name')->all(),'id','name');}
    protected function findModel($id){if(($model=KrsBlock::find()->with(['student.user','studyProgram'])->where(['krs_blocks.id'=>$id])->one())!==null)return $model;throw new NotFoundHttpException('Data Cekal KRS tidak ditemukan.');}
}
