<?php
namespace backend\controllers;
use backend\models\{AcademicCalendar,KrsBlock,KrsRegistration,KrsRegistrationItem,LectureClass,StudyProgram,StudyProgramSetting,StudentSemesterStatus};use common\models\Student;use Yii;use yii\data\ActiveDataProvider;use yii\filters\{AccessControl,VerbFilter};use yii\helpers\ArrayHelper;use yii\web\{Controller,NotFoundHttpException};
class KrsRegistrationController extends Controller
{
    public function behaviors(){return ['access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['@']]]],'verbs'=>['class'=>VerbFilter::class,'actions'=>['delete'=>['POST'],'add-courses'=>['POST'],'remove-course'=>['POST'],'validate'=>['POST']]]];}
    public function actionIndex($academic_period=null,$study_program_id=null,$status=null,$q=null){$periods=$this->periodOptions();$programs=$this->programOptions();$academic_period=$academic_period?:array_key_first($periods);$query=KrsRegistration::find()->alias('kr')->joinWith(['student.user','studyProgram'])->with('lectureClasses.curriculum.subject')->andFilterWhere(['kr.academic_period'=>$academic_period,'kr.study_program_id'=>$study_program_id,'kr.status'=>$status]);if(trim((string)$q)!=='')$query->andWhere(['or',['like','students.student_nationality_number',$q],['like','users.name',$q]]);$dataProvider=new ActiveDataProvider(['query'=>$query->orderBy('users.name'),'pagination'=>['pageSize'=>10],'sort'=>false]);return $this->render('index',compact('dataProvider','periods','programs','academic_period','study_program_id','status','q'));}
    public function actionCreate(){$model=new KrsRegistration(['academic_period'=>array_key_first($this->periodOptions()),'semester'=>1,'maximum_credits'=>24,'status'=>KrsRegistration::STATUS_DRAFT]);return $this->saveForm($model,'create','KRS berhasil dibuat.');}public function actionUpdate($id){return $this->saveForm($this->findModel($id),'update','KRS berhasil diperbarui.');}
    public function actionView($id){return $this->render('view',['model'=>$this->findModel($id)]);}
    public function actionCourses($id){$model=$this->findModel($id);$selectedIds=KrsRegistrationItem::find()->where(['krs_registration_id'=>$id])->select('lecture_class_id')->column();$classes=LectureClass::find()->alias('lc')->joinWith(['curriculum c','curriculum.subject subject'])->with(['schedules.startTimeSlot','schedules.endTimeSlot','schedules.lectureRoom','lectureSystem'])->where(['lc.academic_period'=>$model->academic_period,'c.study_program_id'=>$model->study_program_id])->andWhere(['not in','lc.id',$selectedIds])->orderBy(['c.semester'=>SORT_ASC,'subject.name'=>SORT_ASC])->all();return $this->render('courses',compact('model','classes'));}
    public function actionAddCourses($id){$model=$this->findModel($id);if($message=$this->processBlockMessage($model))return $this->asJson(['success'=>false,'message'=>$message]);$ids=array_unique(array_filter((array)Yii::$app->request->post('lecture_class_ids')));$current=$model->totalCredits;$added=0;foreach(LectureClass::find()->with('curriculum.subject')->where(['id'=>$ids,'academic_period'=>$model->academic_period])->all() as $class){$credits=(int)$class->curriculum->subject->credits;if($current+$credits>$model->maximum_credits)continue;$item=new KrsRegistrationItem(['krs_registration_id'=>$id,'lecture_class_id'=>$class->id]);if($item->save()){$current+=$credits;$added++;}}return $this->asJson(['success'=>true,'message'=>"{$added} mata kuliah ditambahkan. Total {$current} SKS."]);}
    public function actionRemoveCourse($id,$item_id){$item=KrsRegistrationItem::findOne(['id'=>$item_id,'krs_registration_id'=>$id]);if(!$item)throw new NotFoundHttpException('Mata kuliah KRS tidak ditemukan.');$item->delete();return $this->asJson(['success'=>true,'message'=>'Mata kuliah berhasil dihapus dari KRS.']);}
    public function actionValidate($id){$model=$this->findModel($id);if($message=$this->processBlockMessage($model))return $this->asJson(['success'=>false,'message'=>$message]);if(!$model->items)return $this->asJson(['success'=>false,'message'=>'KRS belum memiliki mata kuliah.']);$model->status=KrsRegistration::STATUS_VALIDATED;$model->validated_at=date('Y-m-d H:i:s');$model->validated_by=Yii::$app->user->id;if($model->save())return $this->asJson(['success'=>true,'message'=>'KRS berhasil divalidasi.']);return $this->asJson(['success'=>false,'message'=>implode(' ',$model->getFirstErrors())]);}
    public function actionDelete($id){$this->findModel($id)->delete();return Yii::$app->request->isAjax?$this->asJson(['success'=>true,'message'=>'KRS berhasil dihapus.']):$this->redirect(['index']);}
    private function processBlockMessage($model){$block=KrsBlock::findOne(['student_id'=>$model->student_id,'academic_period'=>$model->academic_period]);if($block&&$block->hasBlock){$types=[];foreach(KrsBlock::blockAttributes() as $a=>$label)if($block->$a)$types[]=$label;return 'Mahasiswa terkena Cekal '.implode(', ',$types).'.';}$setting=StudyProgramSetting::findOne(['study_program_id'=>$model->study_program_id,'academic_period'=>$model->academic_period]);if($setting&&!$setting->krs_enabled)return 'Proses KRS untuk program studi ini sedang dinonaktifkan.';return null;}
    private function saveForm($model,$view,$message){if($model->load(Yii::$app->request->post())&&$model->save()){Yii::$app->session->setFlash('success',$message);return $this->redirect(['view','id'=>$model->id]);}return $this->render($view,['model'=>$model,'periods'=>$this->periodOptions(),'programs'=>$this->programOptions(),'students'=>ArrayHelper::map(Student::find()->joinWith('user')->orderBy('users.name')->all(),'id',static fn($s)=>$s->student_nationality_number.' - '.$s->user->name)]);}
    private function periodOptions(){return array_combine($p=AcademicCalendar::find()->select('period')->distinct()->orderBy(['period'=>SORT_DESC])->column(),$p)?:[];}private function programOptions(){return ArrayHelper::map(StudyProgram::find()->where(['is_active'=>1])->orderBy('name')->all(),'id','name');}
    protected function findModel($id){if(($model=KrsRegistration::find()->with(['student.user','studyProgram.faculty','items.lectureClass.curriculum.subject','items.lectureClass.schedules.startTimeSlot','items.lectureClass.schedules.endTimeSlot','items.lectureClass.schedules.lectureRoom'])->where(['krs_registrations.id'=>$id])->one())!==null)return $model;throw new NotFoundHttpException('KRS tidak ditemukan.');}
}
