<?php
namespace backend\controllers;
use backend\models\{AcademicCalendar,CourseClass,CurriculumYear,LectureClass,LectureClassMeeting,LectureRoom,LectureSystem,StudyProgram,StudyProgramCurriculum,TimeSlot}; use Yii; use yii\data\ActiveDataProvider; use yii\db\Query; use yii\filters\{AccessControl,VerbFilter}; use yii\helpers\ArrayHelper; use yii\web\{Controller,NotFoundHttpException};
class LectureClassController extends Controller
{
    public function behaviors(){return ['access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['@']]]],'verbs'=>['class'=>VerbFilter::class,'actions'=>['delete'=>['POST'],'delete-all'=>['POST'],'generate'=>['GET','POST'],'meeting-delete'=>['POST'],'plan-meetings'=>['POST']]]];}
    public function actionIndex($academic_period=null,$study_program_id=null,$curriculum_year_id=null,$lecture_system_id=null,$course_class_id=null,$q=null)
    {
        $filters=$this->filterOptions();$academic_period=$academic_period?:array_key_first($filters['academicPeriods']);$study_program_id=$study_program_id?:array_key_first($filters['studyPrograms']);$curriculum_year_id=$curriculum_year_id?:array_key_first($filters['curriculumYears']);
        $query=LectureClass::find()->alias('lc')->joinWith(['curriculum.subject subject','curriculum.curriculumYear curriculumYear','curriculum.studyProgram studyProgram','lectureSystem','courseClass'])->with(['lecturers.employee.user','schedules.startTimeSlot','schedules.endTimeSlot','schedules.lectureRoom'])->andFilterWhere(['lc.academic_period'=>$academic_period,'study_program_curricula.study_program_id'=>$study_program_id,'study_program_curricula.curriculum_year_id'=>$curriculum_year_id,'lc.lecture_system_id'=>$lecture_system_id,'lc.course_class_id'=>$course_class_id]);
        if(trim((string)$q)!=='')$query->andWhere(['or',['like','subject.code',$q],['like','subject.name',$q],['like','lc.name',$q]]);
        $dataProvider=new ActiveDataProvider(['query'=>$query->orderBy(['subject.code'=>SORT_ASC,'lc.name'=>SORT_ASC]),'pagination'=>['pageSize'=>10]]);
        return $this->render('index',compact('dataProvider','academic_period','study_program_id','curriculum_year_id','lecture_system_id','course_class_id','q')+$filters);
    }
    public function actionCreate($academic_period=null,$study_program_id=null,$curriculum_year_id=null)
    {
        $model=new LectureClass(['academic_period'=>$academic_period,'capacity'=>40,'meeting_count'=>16]);$this->applyDefaults($model,$study_program_id,$curriculum_year_id);
        if($model->load(Yii::$app->request->post())&&$this->persist($model)){Yii::$app->session->setFlash('success','Kelas Kuliah berhasil ditambahkan.');return $this->redirect($this->redirectParams($model));}
        return $this->render('create',$this->formParams($model,$study_program_id,$curriculum_year_id));
    }
    public function actionUpdate($id){$model=$this->findModel($id);$context=$model->curriculum;if($model->load(Yii::$app->request->post())&&$this->persist($model)){Yii::$app->session->setFlash('success','Kelas Kuliah berhasil diperbarui.');return $this->redirect($this->redirectParams($model));}return $this->render('update',$this->formParams($model,$context->study_program_id,$context->curriculum_year_id));}
    public function actionView($id){return $this->render('view',['model'=>$this->findModel($id)]);}
    public function actionLecturers($id){return $this->render('lecturers',['model'=>$this->findModel($id)]);}
    public function actionLecturerUpdate($id){$model=$this->findModel($id);if($model->load(Yii::$app->request->post())){$model->lecturer_ids=array_values(array_unique(array_filter((array)$model->lecturer_ids)));if($model->coordinator_lecturer_id&&!in_array($model->coordinator_lecturer_id,$model->lecturer_ids))$model->lecturer_ids[]=$model->coordinator_lecturer_id;$tx=Yii::$app->db->beginTransaction();try{Yii::$app->db->createCommand()->delete('lecture_class_lecturers',['lecture_class_id'=>$model->id])->execute();foreach($model->lecturer_ids as $lecturerId)Yii::$app->db->createCommand()->insert('lecture_class_lecturers',['lecture_class_id'=>$model->id,'lecturer_id'=>$lecturerId,'is_coordinator'=>(int)($lecturerId==$model->coordinator_lecturer_id)])->execute();$tx->commit();Yii::$app->session->setFlash('success','Dosen pengajar berhasil diperbarui.');return $this->redirect(['lecturers','id'=>$id]);}catch(\Throwable $e){$tx->rollBack();$model->addError('lecturer_ids',$e->getMessage());}}return $this->render('lecturer-update',['model'=>$model,'lecturers'=>$this->lecturerOptions()]);}
    public function actionContract($id){$model=$this->findModel($id);if($model->load(Yii::$app->request->post())&&$model->save(false,['contract_content'])){Yii::$app->session->setFlash('success','Kontrak Kuliah berhasil disimpan.');return $this->redirect(['contract','id'=>$id]);}return $this->render('contract',['model'=>$model]);}
    public function actionMeetings($id){$model=$this->findModel($id);$meetings=LectureClassMeeting::find()->with(['startTimeSlot','endTimeSlot','lectureRoom','lecturer.employee.user'])->where(['lecture_class_id'=>$id])->orderBy('meeting_number')->all();return $this->render('meetings',compact('model','meetings'));}
    public function actionMeetingCreate($id){$class=$this->findModel($id);$schedule=$class->schedules[0]??null;$number=(int)LectureClassMeeting::find()->where(['lecture_class_id'=>$id])->max('meeting_number')+1;$model=new LectureClassMeeting(['lecture_class_id'=>$id,'meeting_number'=>$number,'schedule_date'=>date('Y-m-d',strtotime($class->start_date.' +'.max(0,$number-1).' weeks')),'start_time_slot_id'=>$schedule->start_time_slot_id??null,'end_time_slot_id'=>$schedule->end_time_slot_id??null,'lecture_room_id'=>$schedule->lecture_room_id??null,'lecturer_id'=>$class->coordinator_lecturer_id?:($class->lecturer_ids[0]??null),'status'=>'scheduled','credits'=>$class->curriculum->subject->credits,'meeting_type'=>'lecture']);if($model->load(Yii::$app->request->post())&&$model->save()){Yii::$app->session->setFlash('success','Jadwal perkuliahan berhasil ditambahkan.');return $this->redirect(['meetings','id'=>$id]);}return $this->render('meeting-create',$this->meetingParams($class,$model));}
    public function actionMeetingUpdate($id,$meeting_id){$class=$this->findModel($id);$model=$this->findMeeting($id,$meeting_id);if($model->load(Yii::$app->request->post())&&$model->save()){Yii::$app->session->setFlash('success','Jadwal perkuliahan berhasil diperbarui.');return $this->redirect(['meetings','id'=>$id]);}return $this->render('meeting-update',$this->meetingParams($class,$model));}
    public function actionMeetingDelete($id,$meeting_id){$this->findMeeting($id,$meeting_id)->delete();return Yii::$app->request->isAjax?$this->asJson(['success'=>true,'message'=>'Jadwal berhasil dihapus.']):$this->redirect(['meetings','id'=>$id]);}
    public function actionPlanMeetings($id){$class=$this->findModel($id);$schedule=$class->schedules[0]??null;if(!$schedule)return $this->asJson(['success'=>false,'message'=>'Jadwal mingguan kelas belum diatur.']);$created=0;$weekday=(int)$schedule->weekday;$start=new \DateTime($class->start_date);$currentWeekday=(int)$start->format('N');if($currentWeekday!==$weekday)$start->modify('+'.(($weekday-$currentWeekday+7)%7).' days');for($number=1;$number<=$class->meeting_count;$number++){if(LectureClassMeeting::find()->where(['lecture_class_id'=>$id,'meeting_number'=>$number])->exists())continue;$meeting=new LectureClassMeeting(['lecture_class_id'=>$id,'meeting_number'=>$number,'schedule_date'=>(clone $start)->modify('+'.($number-1).' weeks')->format('Y-m-d'),'start_time_slot_id'=>$schedule->start_time_slot_id,'end_time_slot_id'=>$schedule->end_time_slot_id,'lecture_room_id'=>$schedule->lecture_room_id,'lecturer_id'=>$class->coordinator_lecturer_id?:($class->lecturer_ids[0]??null),'status'=>'scheduled','credits'=>$class->curriculum->subject->credits,'meeting_type'=>'lecture','planned_material'=>'Materi pertemuan '.$number]);if($meeting->save())$created++;}return $this->asJson(['success'=>true,'message'=>"{$created} jadwal pertemuan berhasil direncanakan."]);}
    public function actionDelete($id){$m=$this->findModel($id);$m->delete();if(Yii::$app->request->isAjax)return $this->asJson(['success'=>true,'message'=>'Kelas Kuliah berhasil dihapus.']);return $this->redirect(['index']);}
    public function actionDeleteAll($academic_period,$study_program_id,$curriculum_year_id){$ids=StudyProgramCurriculum::find()->select('id')->where(['study_program_id'=>$study_program_id,'curriculum_year_id'=>$curriculum_year_id])->column();$count=LectureClass::deleteAll(['academic_period'=>$academic_period,'study_program_curriculum_id'=>$ids]);if(Yii::$app->request->isAjax)return $this->asJson(['success'=>true,'message'=>"{$count} Kelas Kuliah berhasil dihapus."]);return $this->redirect(['index']);}
    public function actionGenerate($academic_period=null,$study_program_id=null,$curriculum_year_id=null)
    {
        $filters=$this->filterOptions();$academic_period=$academic_period?:array_key_first($filters['academicPeriods']);$study_program_id=$study_program_id?:array_key_first($filters['studyPrograms']);$curriculum_year_id=$curriculum_year_id?:array_key_first($filters['curriculumYears']);$curricula=$this->curriculumOptions($study_program_id,$curriculum_year_id);
        if(Yii::$app->request->isPost){$curriculumId=Yii::$app->request->post('study_program_curriculum_id');$count=max(1,min(26,(int)Yii::$app->request->post('class_count',1)));$systemId=Yii::$app->request->post('lecture_system_id');$capacity=max(1,(int)Yii::$app->request->post('capacity',40));$validCurriculum=StudyProgramCurriculum::find()->where(['id'=>$curriculumId,'study_program_id'=>$study_program_id,'curriculum_year_id'=>$curriculum_year_id])->exists();if(!$validCurriculum){Yii::$app->session->setFlash('error','Mata Kuliah wajib berasal dari Kurikulum Prodi yang dipilih.');return $this->redirect(['generate','academic_period'=>$academic_period,'study_program_id'=>$study_program_id,'curriculum_year_id'=>$curriculum_year_id]);}$dates=$this->periodDates($academic_period);$created=0;for($letter=0;$letter<26&&$created<$count;$letter++){$name=chr(65+$letter);if(LectureClass::find()->where(['academic_period'=>$academic_period,'study_program_curriculum_id'=>$curriculumId,'name'=>$name])->exists())continue;$m=new LectureClass(['academic_period'=>$academic_period,'study_program_curriculum_id'=>$curriculumId,'lecture_system_id'=>$systemId,'name'=>$name,'capacity'=>$capacity,'start_date'=>$dates[0],'end_date'=>$dates[1],'meeting_count'=>16]);if($m->save())$created++;}Yii::$app->session->setFlash('success',"{$created} Kelas Kuliah berhasil dibuat dengan urutan nama alfabetis.");return $this->redirect(['index','academic_period'=>$academic_period,'study_program_id'=>$study_program_id,'curriculum_year_id'=>$curriculum_year_id]);}
        return $this->render('generate',compact('academic_period','study_program_id','curriculum_year_id','curricula')+$filters);
    }
    private function applyDefaults(LectureClass $m,$sp,$year){if(Yii::$app->request->isPost)return;$m->academic_period=$m->academic_period?:array_key_first($this->periodOptions());$dates=$this->periodDates($m->academic_period);$m->start_date=$dates[0];$m->end_date=$dates[1];$m->lecture_system_id=LectureSystem::find()->select('id')->orderBy('id')->scalar();}
    private function formParams(LectureClass $m,$sp,$year){$curr=$m->curriculum;$sp=$sp?:($curr->study_program_id??null);$year=$year?:($curr->curriculum_year_id??null);$lecturerRows=(new Query())->select(['id'=>'l.id','name'=>'u.name'])->from(['l'=>'lectures'])->innerJoin(['e'=>'employees'],'e.id=l.employee_id')->innerJoin(['u'=>'users'],'u.id=e.user_id')->orderBy('u.name')->all();return ['model'=>$m,'studyProgramId'=>$sp,'curriculumYearId'=>$year,'curricula'=>$this->curriculumOptions($sp,$year),'academicPeriods'=>$this->periodOptions(),'courseClasses'=>ArrayHelper::map(CourseClass::find()->orderBy('name')->all(),'id','name'),'lectureSystems'=>ArrayHelper::map(LectureSystem::find()->orderBy('name')->all(),'id','name'),'lecturers'=>ArrayHelper::map($lecturerRows,'id','name'),'timeSlots'=>ArrayHelper::map(TimeSlot::find()->orderBy('time')->all(),'id',static fn($s)=>substr($s->time,0,5)),'lectureRooms'=>ArrayHelper::map(LectureRoom::find()->where(['is_active'=>1])->orderBy('name')->all(),'id','name')];}
    private function lecturerOptions(){return ArrayHelper::map((new Query())->select(['id'=>'l.id','name'=>'u.name'])->from(['l'=>'lectures'])->innerJoin(['e'=>'employees'],'e.id=l.employee_id')->innerJoin(['u'=>'users'],'u.id=e.user_id')->orderBy('u.name')->all(),'id','name');}
    private function meetingParams(LectureClass $class,LectureClassMeeting $model){return ['class'=>$class,'model'=>$model,'timeSlots'=>ArrayHelper::map(TimeSlot::find()->orderBy('time')->all(),'id',static fn($s)=>substr($s->time,0,5)),'lectureRooms'=>ArrayHelper::map(LectureRoom::find()->where(['is_active'=>1])->orderBy('name')->all(),'id','name'),'lecturers'=>$this->lecturerOptions()];}
    private function filterOptions(){return ['academicPeriods'=>$this->periodOptions(),'studyPrograms'=>ArrayHelper::map(StudyProgram::find()->orderBy('name')->all(),'id','name'),'curriculumYears'=>ArrayHelper::map(CurriculumYear::find()->orderBy(['year'=>SORT_DESC])->all(),'id','year'),'lectureSystems'=>ArrayHelper::map(LectureSystem::find()->orderBy('name')->all(),'id','name'),'courseClasses'=>ArrayHelper::map(CourseClass::find()->orderBy('name')->all(),'id','name')];}
    private function periodOptions(){return array_combine($p=AcademicCalendar::find()->select('period')->distinct()->orderBy(['period'=>SORT_DESC])->column(),$p)?:[date('Y').'/'.(date('Y')+1).' Ganjil'=>date('Y').'/'.(date('Y')+1).' Ganjil'];}
    private function periodDates($period){$q=AcademicCalendar::find()->where(['period'=>$period]);return [$q->min('start_date')?:date('Y-m-d'),$q->max('end_date')?:date('Y-m-d',strtotime('+5 months'))];}
    private function curriculumOptions($sp,$year){return ArrayHelper::map(StudyProgramCurriculum::find()->joinWith('subject')->where(['study_program_curricula.study_program_id'=>$sp,'study_program_curricula.curriculum_year_id'=>$year])->orderBy('subjects.name')->all(),'id',static fn($m)=>$m->subject->code.' - '.$m->subject->name);}
    private function redirectParams($m){$c=$m->curriculum;return ['index','academic_period'=>$m->academic_period,'study_program_id'=>$c->study_program_id,'curriculum_year_id'=>$c->curriculum_year_id];}
    private function persist(LectureClass $model){$transaction=Yii::$app->db->beginTransaction();try{if(!$model->save()||!$model->saveRelations()){$transaction->rollBack();return false;}$transaction->commit();return true;}catch(\Throwable $exception){$transaction->rollBack();$model->addError('name',$exception->getMessage());return false;}}
    protected function findModel($id){if(($m=LectureClass::find()->with(['curriculum.subject','curriculum.studyProgram','curriculum.curriculumYear','lectureSystem','courseClass','lecturers.employee.user','schedules.startTimeSlot','schedules.endTimeSlot','schedules.lectureRoom'])->where(['lecture_classes.id'=>$id])->one())!==null)return $m;throw new NotFoundHttpException('Kelas Kuliah tidak ditemukan.');}
    protected function findMeeting($classId,$id){if(($m=LectureClassMeeting::findOne(['id'=>$id,'lecture_class_id'=>$classId]))!==null)return $m;throw new NotFoundHttpException('Jadwal perkuliahan tidak ditemukan.');}
}
