<?php
namespace backend\controllers;
use backend\models\{AcademicCalendar,CurriculumYear,StudyProgram,StudyProgramSetting,University};use Yii;use yii\filters\{AccessControl,VerbFilter};use yii\helpers\ArrayHelper;use yii\web\{Controller,NotFoundHttpException};
class StudyProgramSettingController extends Controller
{
    public function behaviors(){return ['access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['@']]]],'verbs'=>['class'=>VerbFilter::class,'actions'=>['delete'=>['POST'],'toggle'=>['POST'],'curriculum'=>['POST']]]];}
    public function actionIndex($academic_period=null,$university_id=null){$periods=$this->periodOptions();$universities=ArrayHelper::map(University::find()->orderBy('unit_name')->all(),'id','unit_name');$academic_period=$academic_period?:array_key_first($periods);$university_id=$university_id?:array_key_first($universities);$programs=StudyProgram::find()->with('faculty')->where(['is_active'=>1])->orderBy(['faculty_id'=>SORT_ASC,'name'=>SORT_ASC])->all();$settings=StudyProgramSetting::find()->with('curriculumYear')->where(['academic_period'=>$academic_period])->indexBy('study_program_id')->all();$curriculumYears=ArrayHelper::map(CurriculumYear::find()->orderBy(['year'=>SORT_DESC])->all(),'id','year');return $this->render('index',compact('periods','universities','academic_period','university_id','programs','settings','curriculumYears'));}
    public function actionCreate($study_program_id=null,$academic_period=null){$model=new StudyProgramSetting(['academic_period'=>$academic_period?:array_key_first($this->periodOptions()),'study_program_id'=>$study_program_id]);return $this->saveForm($model,'create','Pengaturan Prodi berhasil ditambahkan.');}
    public function actionUpdate($id){return $this->saveForm($this->findModel($id),'update','Pengaturan Prodi berhasil diperbarui.');}
    public function actionView($id){return $this->render('view',['model'=>$this->findModel($id)]);}
    public function actionToggle($study_program_id,$academic_period){$model=StudyProgramSetting::findOne(compact('study_program_id','academic_period'))??new StudyProgramSetting(compact('study_program_id','academic_period'));$attribute=Yii::$app->request->post('attribute');if(!in_array($attribute,StudyProgramSetting::booleanAttributes(),true))return $this->asJson(['success'=>false,'message'=>'Jenis pengaturan tidak valid.']);$model->$attribute=(bool)Yii::$app->request->post('value');if($model->save())return $this->asJson(['success'=>true,'message'=>'Pengaturan Prodi berhasil diperbarui.','id'=>$model->id]);return $this->asJson(['success'=>false,'message'=>implode(' ',$model->getFirstErrors())]);}
    public function actionCurriculum($study_program_id,$academic_period){$model=StudyProgramSetting::findOne(compact('study_program_id','academic_period'))??new StudyProgramSetting(compact('study_program_id','academic_period'));$model->new_student_curriculum_year_id=Yii::$app->request->post('value')?:null;if($model->save())return $this->asJson(['success'=>true,'message'=>'Kurikulum mahasiswa baru berhasil diperbarui.','id'=>$model->id]);return $this->asJson(['success'=>false,'message'=>implode(' ',$model->getFirstErrors())]);}
    public function actionDelete($id){$this->findModel($id)->delete();return Yii::$app->request->isAjax?$this->asJson(['success'=>true,'message'=>'Pengaturan Prodi berhasil dihapus.']):$this->redirect(['index']);}
    private function saveForm($model,$view,$message){if($model->load(Yii::$app->request->post())&&$model->save()){Yii::$app->session->setFlash('success',$message);return $this->redirect(['view','id'=>$model->id]);}return $this->render($view,['model'=>$model,'periods'=>$this->periodOptions(),'programs'=>ArrayHelper::map(StudyProgram::find()->orderBy('name')->all(),'id','name'),'curriculumYears'=>ArrayHelper::map(CurriculumYear::find()->orderBy(['year'=>SORT_DESC])->all(),'id','year')]);}
    private function periodOptions(){return array_combine($p=AcademicCalendar::find()->select('period')->distinct()->orderBy(['period'=>SORT_DESC])->column(),$p)?:[];}
    protected function findModel($id){if(($model=StudyProgramSetting::find()->with(['studyProgram','curriculumYear'])->where(['study_program_settings.id'=>$id])->one())!==null)return $model;throw new NotFoundHttpException('Pengaturan Prodi tidak ditemukan.');}
}
