<?php
namespace backend\controllers;
use backend\models\{AcademicCalendar,KrsBlock,StudyProgram,StudentSemesterStatus};use common\models\Student;use Yii;use yii\data\ActiveDataProvider;use yii\db\Query;use yii\filters\{AccessControl,VerbFilter};use yii\helpers\ArrayHelper;use yii\web\{Controller,NotFoundHttpException};
class StudentSemesterStatusController extends Controller
{
    public function behaviors(){return ['access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['@']]]],'verbs'=>['class'=>VerbFilter::class,'actions'=>['delete'=>['POST'],'generate'=>['POST']]]];}
    public function actionIndex($academic_period=null){$periods=$this->periodOptions();$academic_period=$academic_period?:array_key_first($periods);$programs=StudyProgram::find()->with('faculty')->where(['is_active'=>1])->orderBy(['faculty_id'=>SORT_ASC,'name'=>SORT_ASC])->all();$counts=(new Query())->select(['study_program_id','status','total'=>'COUNT(*)'])->from(StudentSemesterStatus::tableName())->where(['academic_period'=>$academic_period])->groupBy(['study_program_id','status'])->all();$summary=[];foreach($counts as $row)$summary[$row['study_program_id']][$row['status']]=(int)$row['total'];$total=[StudentSemesterStatus::STATUS_ACTIVE=>0,StudentSemesterStatus::STATUS_LEAVE=>0,StudentSemesterStatus::STATUS_INACTIVE=>0];foreach($summary as $values)foreach($total as $status=>$_)$total[$status]+=$values[$status]??0;return $this->render('index',compact('periods','academic_period','programs','summary','total'));}
    public function actionList($academic_period=null,$study_program_id=null){$query=StudentSemesterStatus::find()->with(['student.user','studyProgram'])->andFilterWhere(['academic_period'=>$academic_period,'study_program_id'=>$study_program_id]);$dataProvider=new ActiveDataProvider(['query'=>$query->orderBy('id'),'pagination'=>['pageSize'=>20]]);return $this->render('list',compact('dataProvider','academic_period','study_program_id'));}
    public function actionGenerate($academic_period){$created=0;$programIds=StudyProgram::find()->where(['is_active'=>1])->orderBy('id')->select('id')->column();foreach(Student::find()->orderBy('id')->all() as $index=>$student){if(StudentSemesterStatus::find()->where(['student_id'=>$student->id,'academic_period'=>$academic_period])->exists())continue;$block=KrsBlock::findOne(['student_id'=>$student->id,'academic_period'=>$academic_period]);$model=new StudentSemesterStatus(['student_id'=>$student->id,'academic_period'=>$academic_period,'study_program_id'=>$block->study_program_id??$programIds[$index%count($programIds)],'semester'=>$block->current_semester??(($index%8)+1),'status'=>$block&&$block->hasBlock?StudentSemesterStatus::STATUS_LEAVE:StudentSemesterStatus::STATUS_ACTIVE,'notes'=>'Dibuat otomatis dari proses Status Semester.']);if($model->save())$created++;}return Yii::$app->request->isAjax?$this->asJson(['success'=>true,'message'=>"{$created} status semester berhasil dibuat."]):$this->redirect(['index','academic_period'=>$academic_period]);}
    public function actionCreate(){$model=new StudentSemesterStatus(['academic_period'=>array_key_first($this->periodOptions()),'semester'=>1,'status'=>StudentSemesterStatus::STATUS_ACTIVE]);return $this->saveForm($model,'create','Status Semester berhasil ditambahkan.');}
    public function actionUpdate($id){return $this->saveForm($this->findModel($id),'update','Status Semester berhasil diperbarui.');}public function actionView($id){return $this->render('view',['model'=>$this->findModel($id)]);}
    public function actionDelete($id){$this->findModel($id)->delete();return Yii::$app->request->isAjax?$this->asJson(['success'=>true,'message'=>'Status Semester berhasil dihapus.']):$this->redirect(['index']);}
    private function saveForm($model,$view,$message){if($model->load(Yii::$app->request->post())&&$model->save()){Yii::$app->session->setFlash('success',$message);return $this->redirect(['view','id'=>$model->id]);}return $this->render($view,['model'=>$model,'periods'=>$this->periodOptions(),'programs'=>ArrayHelper::map(StudyProgram::find()->orderBy('name')->all(),'id','name'),'students'=>ArrayHelper::map(Student::find()->joinWith('user')->orderBy('users.name')->all(),'id',static fn($s)=>$s->student_nationality_number.' - '.$s->user->name)]);}
    private function periodOptions(){return array_combine($p=AcademicCalendar::find()->select('period')->distinct()->orderBy(['period'=>SORT_DESC])->column(),$p)?:[];}protected function findModel($id){if(($model=StudentSemesterStatus::find()->with(['student.user','studyProgram'])->where(['student_semester_statuses.id'=>$id])->one())!==null)return $model;throw new NotFoundHttpException('Status Semester tidak ditemukan.');}
}
