<?php
namespace backend\controllers;
use backend\models\{AcademicCalendar,LectureClass,StudyProgram,University,WeeklyScheduleReportForm};
use common\models\Student;
use kartik\mpdf\Pdf;
use Yii;use yii\filters\AccessControl;use yii\helpers\ArrayHelper;use yii\web\{Controller,NotFoundHttpException,Response};
class WeeklyScheduleReportController extends Controller
{
    public function behaviors(){return ['access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['@']]]]];}
    public function actionIndex(){ $model=new WeeklyScheduleReportForm(['academic_period'=>array_key_first($this->periodOptions()),'study_program_id'=>StudyProgram::find()->select('id')->orderBy('name')->scalar(),'semester'=>1,'format'=>'html','use_letterhead'=>1]);if($model->load(Yii::$app->request->get())&&$model->validate()){if($model->format==='pdf')return $this->redirect(['print']+$model->attributes);return $this->actionView($model->attributes);}return $this->render('index',$this->formParams($model));}
    public function actionView(array $params=[]){$model=new WeeklyScheduleReportForm();$model->setAttributes($params?:Yii::$app->request->get());if(!$model->validate())throw new NotFoundHttpException('Filter laporan tidak valid.');return $this->render('view',$this->reportParams($model));}
    public function actionPrint(){ $model=new WeeklyScheduleReportForm();$model->load(Yii::$app->request->get(),'');if(!$model->validate())throw new NotFoundHttpException('Filter laporan tidak valid.');$params=$this->reportParams($model);Yii::$app->response->format=Response::FORMAT_RAW;$pdf=new Pdf(['mode'=>Pdf::MODE_UTF8,'format'=>Pdf::FORMAT_A4,'orientation'=>Pdf::ORIENT_LANDSCAPE,'destination'=>Pdf::DEST_BROWSER,'filename'=>'Laporan-Jadwal-Mingguan.pdf','content'=>$this->renderPartial('_report', $params),'cssFile'=>'@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css','cssInline'=>'body{font-family:Arial,sans-serif;font-size:9pt}.report{padding:10px}.title{text-align:center;font-weight:bold;margin-bottom:22px}.meta{margin-top:0}.meta td{padding:2px 8px}.schedule{width:100%;border-collapse:collapse;margin-top:10px}.schedule th,.schedule td{border:1px solid #555;padding:5px}.schedule th{text-align:center}']);return $pdf->render();}
    private function formParams($model){return ['model'=>$model,'periods'=>$this->periodOptions(),'studyPrograms'=>ArrayHelper::map(StudyProgram::find()->where(['is_active'=>1])->orderBy('name')->all(),'id','name'),'semesters'=>array_combine(range(1,8),range(1,8)),'students'=>ArrayHelper::map(Student::find()->joinWith('user')->orderBy('users.name')->all(),'id',static fn($s)=>$s->student_nationality_number.' - '.$s->user->name)];}
    private function reportParams(WeeklyScheduleReportForm $model){$program=StudyProgram::find()->with('faculty')->where(['study_programs.id'=>$model->study_program_id])->one();if(!$program)throw new NotFoundHttpException('Program Studi tidak ditemukan.');$student=$model->student_id?Student::find()->with('user')->where(['students.id'=>$model->student_id])->one():null;$classes=LectureClass::find()->alias('lc')->joinWith(['curriculum c','curriculum.subject subject'])->with(['schedules.startTimeSlot','schedules.endTimeSlot','schedules.lectureRoom','lecturers.employee.user'])->where(['lc.academic_period'=>$model->academic_period,'c.study_program_id'=>$model->study_program_id,'c.semester'=>$model->semester])->orderBy(['subject.name'=>SORT_ASC])->all();return ['filter'=>$model,'program'=>$program,'student'=>$student,'classes'=>$classes,'university'=>University::find()->orderBy('id')->one()];}
    private function periodOptions(){return array_combine($p=AcademicCalendar::find()->select('period')->distinct()->orderBy(['period'=>SORT_DESC])->column(),$p)?:[date('Y').'/'.(date('Y')+1).' Ganjil'=>date('Y').'/'.(date('Y')+1).' Ganjil'];}
}
