<?php use backend\models\KrsBlock;use common\widgets\Alert;use kartik\grid\GridView;use kartik\select2\Select2;use yii\helpers\{Html,Url};$this->title='Cekal KRS';?>
<?=Alert::widget()?><div class="d-flex align-items-baseline mb-3"><h1 class="mb-0 mr-2">Cekal KRS</h1><span class="text-muted">Pemberian Cekal Mahasiswa</span></div>
<div class="card card-warning card-outline"><div class="card-body"><?=Html::beginForm(['index'],'get',['id'=>'krs-block-filter'])?><div class="row"><div class="col-md-4"><label class="text-warning">Periode</label><?=Select2::widget(['name'=>'academic_period','value'=>$academic_period,'data'=>$periods])?></div><div class="col-md-4"><label class="text-warning">Program Studi</label><?=Select2::widget(['name'=>'study_program_id','value'=>$study_program_id,'data'=>$programs])?></div><div class="col-md-4"><label class="text-warning">Tahun Masuk</label><?=Html::dropDownList('entry_year',$entry_year,$entryYears,['class'=>'form-control','prompt'=>'-- Semua --'])?></div></div><?=Html::endForm()?></div></div>
<?=GridView::widget(['id'=>'krs-block-grid','dataProvider'=>$dataProvider,'pjax'=>true,'pjaxSettings'=>['neverTimeout'=>true,'options'=>['id'=>'krs-block-pjax']],'panel'=>['heading'=>'<i class="fas fa-user-lock mr-1"></i> Daftar Cekal KRS','type'=>GridView::TYPE_DARK,'before'=>Html::beginForm(['index'],'get',['class'=>'form-inline','data-pjax'=>1]).Html::hiddenInput('academic_period',$academic_period).Html::hiddenInput('study_program_id',$study_program_id).Html::hiddenInput('entry_year',$entry_year).'<div class="input-group">'.Html::textInput('q',$q,['class'=>'form-control','placeholder'=>'Cari NIM atau mahasiswa']).'<div class="input-group-append">'.Html::submitButton('<i class="fas fa-search"></i>',['class'=>'btn btn-success']).Html::a('<i class="fas fa-sync-alt"></i>',['index','academic_period'=>$academic_period,'study_program_id'=>$study_program_id],['class'=>'btn btn-primary','data-pjax'=>1]).'</div></div>'.Html::endForm()],'toolbar'=>[['content'=>Html::a('<i class="fas fa-plus"></i>',['create'],['class'=>'btn btn-success','title'=>'Tambah Cekal KRS','data-pjax'=>0])]],'columns'=>[['attribute'=>'student_id','label'=>'NIM','value'=>static fn($m)=>$m->student->student_nationality_number],['label'=>'Nama Mahasiswa','value'=>static fn($m)=>$m->student->user->name],['attribute'=>'study_program_id','label'=>'Prodi','value'=>static fn($m)=>$m->studyProgram->name],['attribute'=>'entry_year','label'=>'Tahun Masuk'],['attribute'=>'current_semester','label'=>'Smt'],...array_map(static function($attribute){return ['attribute'=>$attribute,'label'=>KrsBlock::blockAttributes()[$attribute],'format'=>'raw','value'=>static fn($m)=>Html::checkbox($attribute,$m->$attribute,['class'=>'js-toggle-block','data-id'=>$m->id,'data-attribute'=>$attribute])];},array_keys(backend\models\KrsBlock::blockAttributes())),['class'=>'kartik\grid\ActionColumn','header'=>'Aksi','width'=>'120px','template'=>'{view} {update} {delete}','buttons'=>['view'=>static fn($url)=>Html::a('<i class="fas fa-eye"></i>',$url,['class'=>'btn btn-info btn-sm','data-pjax'=>0]),'update'=>static fn($url)=>Html::a('<i class="fas fa-edit"></i>',$url,['class'=>'btn btn-primary btn-sm','data-pjax'=>0]),'delete'=>static fn($url)=>Html::button('<i class="fas fa-trash"></i>',['class'=>'btn btn-danger btn-sm js-delete-block','data-url'=>$url])]]],'summary'=>'Menampilkan <b>{begin}-{end}</b> dari <b>{totalCount}</b> data.','emptyText'=>'Data cekal belum tersedia.'])?>
<?php $toggleUrl=Url::to(['toggle']);$js=<<<'JS'
$('#krs-block-filter select').on('change',function(){window.location=$('#krs-block-filter').attr('action')+'?'+$('#krs-block-filter').serialize();});
$(document).on('change','.js-toggle-block',function(){var cb=this;$.post('__TOGGLE_URL__?id='+$(cb).data('id'),{_csrf:yii.getCsrfToken(),attribute:$(cb).data('attribute'),value:cb.checked?1:0}).done(function(r){if(r.success){Swal.fire({title:'Berhasil',text:r.message,icon:'success',timer:1000,showConfirmButton:false});}else{cb.checked=!cb.checked;Swal.fire('Gagal',r.message,'error');}}).fail(function(){cb.checked=!cb.checked;Swal.fire('Gagal','Status cekal tidak dapat diperbarui.','error');});});
$(document).on('click','.js-delete-block',function(){var url=$(this).data('url');Swal.fire({title:'Hapus data cekal?',text:'Data yang dihapus tidak dapat dikembalikan.',icon:'warning',showCancelButton:true,confirmButtonText:'Ya, Hapus',cancelButtonText:'Batal'}).then(function(x){if(!x.isConfirmed)return;$.post(url,{_csrf:yii.getCsrfToken()}).done(function(r){Swal.fire('Berhasil',r.message,'success').then(function(){$.pjax.reload({container:'#krs-block-pjax'});});});});});
JS;$this->registerJs(str_replace('__TOGGLE_URL__',$toggleUrl,$js));?>
