<?php
use kartik\detail\DetailView;
use yii\helpers\Html;
use yii\helpers\Url;
$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Kelas Perkuliahan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-class-view"><div class="d-flex justify-content-between align-items-center mb-4"><h1><?= Html::encode($this->title) ?></h1><div><?= Html::a('<i class="fas fa-arrow-left"></i> Kembali ke Daftar', ['index'], ['class' => 'btn btn-outline-secondary']) ?> <?= Html::a('<i class="fas fa-edit"></i> Ubah', ['update', 'id' => $model->id], ['class' => 'btn btn-warning ml-2']) ?> <?= Html::button('<i class="fas fa-trash"></i> Hapus', ['class' => 'btn btn-danger ml-2 js-delete-course-class-detail', 'data-url' => Url::to(['delete', 'id' => $model->id])]) ?></div></div><?= DetailView::widget(['model' => $model, 'mode' => DetailView::MODE_VIEW, 'panel' => ['heading' => '<i class="fas fa-chalkboard"></i> Detail Kelas Perkuliahan', 'type' => DetailView::TYPE_PRIMARY], 'attributes' => ['code', 'name', ['attribute' => 'created_at', 'format' => ['datetime', 'php:d M Y H:i']], ['attribute' => 'updated_at', 'format' => ['datetime', 'php:d M Y H:i']]]]) ?></div>
<?php $redirectUrl = Url::to(['index']); $this->registerJs("$('.js-delete-course-class-detail').on('click',function(){var url=$(this).data('url');Swal.fire({title:'Hapus Kelas Perkuliahan?',text:'Data yang sudah dihapus tidak dapat dikembalikan.',icon:'warning',showCancelButton:true,confirmButtonColor:'#dc3545',confirmButtonText:'Ya, Hapus',cancelButtonText:'Batal',reverseButtons:true}).then(function(result){if(!result.isConfirmed)return;$.ajax({url:url,type:'POST',dataType:'json',data:{_csrf:yii.getCsrfToken()}}).done(function(response){if(response.success){Swal.fire('Berhasil',response.message,'success').then(function(){window.location.href='" . $redirectUrl . "';});}else{Swal.fire('Gagal',response.message||'Data gagal dihapus.','error');}}).fail(function(){Swal.fire('Gagal','Terjadi kesalahan saat menghapus Kelas Perkuliahan.','error');});});});"); ?>
