<?php
namespace backend\models;
use common\models\Lecture; use common\models\User; use yii\behaviors\BlameableBehavior; use yii\behaviors\TimestampBehavior; use yii\db\ActiveRecord; use yii\db\Expression;
class LectureClass extends ActiveRecord
{
    public $lecturer_ids=[]; public $coordinator_lecturer_id; public $schedule_weekday; public $schedule_start_time_slot_id; public $schedule_end_time_slot_id; public $schedule_lecture_room_id;
    public static function tableName(){return 'lecture_classes';}
    public function behaviors(){return [['class'=>TimestampBehavior::class,'value'=>new Expression('NOW()')],BlameableBehavior::class];}
    public function rules(){return [[['academic_period','study_program_curriculum_id','lecture_system_id','name','capacity','start_date','end_date','meeting_count'],'required'],[['study_program_curriculum_id','course_class_id','lecture_system_id','capacity','meeting_count','created_by','updated_by','coordinator_lecturer_id','schedule_weekday','schedule_start_time_slot_id','schedule_end_time_slot_id','schedule_lecture_room_id'],'integer'],[['lecturer_ids'],'each','rule'=>['integer']],['contract_content','string'],['academic_period','string','max'=>50],['name','filter','filter'=>static fn($v)=>strtoupper(trim($v))],['name','string','max'=>20],['capacity','integer','min'=>1],['meeting_count','integer','min'=>1,'max'=>40],[['start_date','end_date'],'date','format'=>'php:Y-m-d'],['end_date','compare','compareAttribute'=>'start_date','operator'=>'>=','type'=>'date'],[['academic_period','study_program_curriculum_id','name'],'unique','targetAttribute'=>['academic_period','study_program_curriculum_id','name'],'message'=>'Nama kelas sudah digunakan untuk mata kuliah dan periode tersebut.'],['study_program_curriculum_id','exist','targetClass'=>StudyProgramCurriculum::class,'targetAttribute'=>['study_program_curriculum_id'=>'id']],['course_class_id','exist','skipOnEmpty'=>true,'targetClass'=>CourseClass::class,'targetAttribute'=>['course_class_id'=>'id']],['lecture_system_id','exist','targetClass'=>LectureSystem::class,'targetAttribute'=>['lecture_system_id'=>'id']]];}
    public function afterFind(){parent::afterFind();$this->lecturer_ids=$this->getLecturers()->select('lectures.id')->column();$this->coordinator_lecturer_id=(new \yii\db\Query())->select('lecturer_id')->from('lecture_class_lecturers')->where(['lecture_class_id'=>$this->id,'is_coordinator'=>1])->scalar()?:null;$s=$this->schedules[0]??null;if($s){$this->schedule_weekday=$s->weekday;$this->schedule_start_time_slot_id=$s->start_time_slot_id;$this->schedule_end_time_slot_id=$s->end_time_slot_id;$this->schedule_lecture_room_id=$s->lecture_room_id;}}
    public function saveRelations(){ $tx=self::getDb()->beginTransaction();try{self::getDb()->createCommand()->delete('lecture_class_lecturers',['lecture_class_id'=>$this->id])->execute();foreach((array)$this->lecturer_ids as $id)self::getDb()->createCommand()->insert('lecture_class_lecturers',['lecture_class_id'=>$this->id,'lecturer_id'=>$id,'is_coordinator'=>(int)($id==$this->coordinator_lecturer_id)])->execute();self::getDb()->createCommand()->delete('lecture_class_schedules',['lecture_class_id'=>$this->id])->execute();if($this->schedule_weekday&&$this->schedule_start_time_slot_id&&$this->schedule_end_time_slot_id){$s=new LectureClassSchedule(['lecture_class_id'=>$this->id,'weekday'=>$this->schedule_weekday,'start_time_slot_id'=>$this->schedule_start_time_slot_id,'end_time_slot_id'=>$this->schedule_end_time_slot_id,'lecture_room_id'=>$this->schedule_lecture_room_id]);if(!$s->save())throw new \RuntimeException(implode(' ',$s->getFirstErrors()));}$tx->commit();return true;}catch(\Throwable $e){$tx->rollBack();$this->addError('schedule_weekday',$e->getMessage());return false;}}
    public function getCurriculum(){return $this->hasOne(StudyProgramCurriculum::class,['id'=>'study_program_curriculum_id']);} public function getCourseClass(){return $this->hasOne(CourseClass::class,['id'=>'course_class_id']);} public function getLectureSystem(){return $this->hasOne(LectureSystem::class,['id'=>'lecture_system_id']);} public function getSchedules(){return $this->hasMany(LectureClassSchedule::class,['lecture_class_id'=>'id']);} public function getLecturers(){return $this->hasMany(Lecture::class,['id'=>'lecturer_id'])->viaTable('lecture_class_lecturers',['lecture_class_id'=>'id']);} public function getMeetings(){return $this->hasMany(LectureClassMeeting::class,['lecture_class_id'=>'id'])->orderBy('meeting_number');}
    public function getLecturerNames(){return implode(', ',array_map(static fn($l)=>$l->employee->user->name??'-',$this->lecturers));}
    public function getScheduleLabel(){return implode('<br>',array_map(static fn($s)=>(LectureClassSchedule::dayOptions()[$s->weekday]??'-').', '.substr($s->startTimeSlot->time,0,5).' s.d. '.substr($s->endTimeSlot->time,0,5).($s->lectureRoom?' @ '.$s->lectureRoom->name:''),$this->schedules));}
    public function attributeLabels(){return ['academic_period'=>'Periode Akademik','study_program_curriculum_id'=>'Mata Kuliah','course_class_id'=>'Kelas Mahasiswa','lecture_system_id'=>'Sistem Kuliah','name'=>'Nama Kelas','capacity'=>'Kapasitas','start_date'=>'Tgl. Mulai','end_date'=>'Tgl. Selesai','meeting_count'=>'Jumlah Pertemuan','lecturer_ids'=>'Dosen Pengajar','coordinator_lecturer_id'=>'Penanggung Jawab Mata Kuliah','contract_content'=>'Isi Kontrak Kuliah','schedule_weekday'=>'Hari','schedule_start_time_slot_id'=>'Jam Mulai','schedule_end_time_slot_id'=>'Jam Selesai','schedule_lecture_room_id'=>'Ruang'];}
}
